auths/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from ih_pharmacie.views import home

urlpatterns = [
    path('', home, name="home"),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('userparams/', views.user_params, name='userparams'),
]

ih_pharmacie/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve
from django.conf.urls.static import static
from . import views
from django.conf import settings

handler404 = views.error404
handler500 = views.error500


urlpatterns = [
    path('', views.home, name="home"),
    path('ih_admin/', admin.site.urls),
    path('pharmacy/', include('med.urls')),
    path('auth/', include('auths.urls')),
    path('site/ajax', views.siteAjax, name="site_ajax"),
    path('translation/ajax', views.TranslationAjax, name="translation_ajax"),
]

if settings.DEBUG == False:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_DIR}),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

from ih_pharmacie.views import home

urlpatterns = [
    path('', home, name="home"),

    path('cameg/', views.DrugServedData, name='cameg'),
    path('cameg/create/', views.CamegDataCreateUpdateDelete, name='cameg_create'),
    path('cameg/update/<str:id>/', views.CamegDataCreateUpdateDelete, name='cameg_update'),
    path('cameg/delete/<str:delete>/',views.CamegDataCreateUpdateDelete, name='cameg_delete'),

    path('patient/', views.DrugServedData, name='patient'),
    path('patient/create/', views.PatientDataCreateUpdateDelete, name='patient_create'),
    path('patient/update/<str:id>/', views.PatientDataCreateUpdateDelete, name='patient_update'),
    path('patient/delete/<str:delete>/',views.PatientDataCreateUpdateDelete, name='patient_delete'),
 
    path('ih/', views.DrugServedData, name='ih'),
    path('ih/create/', views.IhDataCreateUpdateDelete, name='ih_create'),
    path('ih/update/<str:id>/', views.IhDataCreateUpdateDelete, name='ih_update'),
    path('ih/delete/<str:delete>/', views.IhDataCreateUpdateDelete, name='ih_delete'),

    path('stock/', views.DrugServedData, name='stock'),
    path('stock/create/', views.StockDataCreateUpdateDelete, name='stock_create'),
    path('stock/update/<str:id>/', views.StockDataCreateUpdateDelete, name='stock_update'),
    path('stock/delete/<str:delete>/', views.StockDataCreateUpdateDelete, name='stock_delete'),

    path('drug/stock_adjustment/', views.DrugServedData, name='stock_adjustment'),
    path('drug/stock_adjustment/create/', views.StockAdjustmentDataCreateUpdateDelete, name='stock_adjustment_create'),
    path('drug/stock_adjustment/update/<str:id>/', views.StockAdjustmentDataCreateUpdateDelete, name='stock_adjustment_update'),
    path('drug/stock_adjustment/delete/<str:delete>/', views.StockAdjustmentDataCreateUpdateDelete, name='stock_adjustment_delete'),

    path('drug/drugs_list/', views.DrugDataCreateUpdateDelete, name='drug'),
    path('drug/drugs_list/create/', views.DrugDataCreateUpdateDelete, name='drug_create'),
    path('drug/drugs_list/update/<int:id>/', views.DrugDataCreateUpdateDelete, name='drug_update'),
    path('drug/drugs_list/delete/<int:delete>/', views.DrugDataCreateUpdateDelete, name='drug_delete'),

    path('drug/drug_supplier/', views.DrugSupplierDataCreateUpdateDelete, name='drug_supplier'),
    path('drug/drug_supplier/create/', views.DrugSupplierDataCreateUpdateDelete,name='drug_supplier_create'),
    path('drug/drug_supplier/update/<int:id>/',views.DrugSupplierDataCreateUpdateDelete, name='drug_supplier_update'),
    path('drug/drug_supplier/delete/<int:delete>/',views.DrugSupplierDataCreateUpdateDelete, name='drug_supplier_delete'),

    path('drug/category/', views.CategoryDataCreateUpdateDelete, name='category'),
    path('drug/category/create/', views.CategoryDataCreateUpdateDelete, name='category_create'),
    path('drug/category/update/<int:id>/', views.CategoryDataCreateUpdateDelete, name='category_update'),
    path('drug/category/delete/<int:delete>/', views.CategoryDataCreateUpdateDelete, name='category_delete'),

    path('drug/year/', views.YearDataCreateUpdateDelete, name='year'),
    path('drug/year/create/', views.YearDataCreateUpdateDelete, name='year_create'),
    path('drug/year/update/<int:id>/', views.YearDataCreateUpdateDelete, name='year_update'),
    path('drug/year/delete/<int:delete>/', views.YearDataCreateUpdateDelete, name='year_delete'),

    path('drug/month/', views.MonthDataCreateUpdateDelete, name='month'),
    path('drug/month/create/', views.MonthDataCreateUpdateDelete, name='month_create'),
    path('drug/month/update/<int:id>/', views.MonthDataCreateUpdateDelete, name='month_update'),
    path('drug/month/delete/<int:delete>/', views.MonthDataCreateUpdateDelete, name='month_delete'),

    path('drug/district/', views.DistrictDataCreateUpdateDelete, name='district'),
    path('drug/district/create/', views.DistrictDataCreateUpdateDelete, name='district_create'),
    path('drug/district/update/<int:id>/',views.DistrictDataCreateUpdateDelete, name='district_update'),
    path('drug/district/delete/<int:delete>/',views.DistrictDataCreateUpdateDelete, name='district_delete'),

    path('drug/site/', views.SiteDataCreateUpdateDelete, name='site'),
    path('drug/site/create/', views.SiteDataCreateUpdateDelete, name='site_create'),
    path('drug/site/update/<int:id>/',views.SiteDataCreateUpdateDelete, name='site_update'),
    path('drug/site/delete/<int:delete>/',views.SiteDataCreateUpdateDelete, name='site_delete'),

    path('drug/translation/', views.TranslationDataCreateUpdateDelete, name='translation'),
    path('drug/translation/create/', views.TranslationDataCreateUpdateDelete, name='translation_create'),
    path('drug/translation/update/<int:id>/', views.TranslationDataCreateUpdateDelete, name='translation_update'),
    path('drug/translation/delete/<int:delete>/', views.TranslationDataCreateUpdateDelete, name='translation_delete'),

    path('drug/language/', views.LanguageUpdate, name='language'),
    path('dashborad/general/', views.Dash, name='dash'),
    path('dashborad/served/', views.ServedEtat, name='dashS'),
]

auths/models.py
from django.db import models
from django.contrib.auth.models import User

from PIL import Image
import os

def user_directory_path(instance, filename):
    return 'profile_pics'

def user_directory_path2(instance, filename):
    return 'profile_pics'

def images_dir(file=""):
    if file != "":
        return os.path.join(os.path.abspath(os.path.dirname('media/images/')), file)
    else:
        return os.path.abspath(os.path.dirname('media/images/'))

def user_path(instance, filename):
    from os.path import basename
    basename(filename)
    filename, fileExtension = os.path.splitext(filename)
    return '{}/{}/{}{}'.format('profile_pics', instance.user.id, hash(filename), fileExtension)

def user_path_thumb(instance, filename):
    from os.path import basename
    basename(filename)
    filename, fileExtension = os.path.splitext(filename)
    return '{}/{}/{}/{}{}{}'.format('profile_pics', instance.user.id, 'thumb', hash(filename), '_thumb', fileExtension)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to=user_path, null=True, blank=True, default="images/DefaultUserIcon.png")
    profile_pic_thumb = models.ImageField(upload_to=user_path_thumb, null=True, blank=True, default="images/DefaultUserIcon.png")
    biography = models.TextField(null=True, blank=True)
    role = models.CharField(max_length=30, null=True, blank=True)
    is_creator = models.BooleanField(default=False, help_text="Designates that this user is in creator's team")
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.profile_pic.path)
        img_thumb = Image.open(self.profile_pic_thumb.path)
        
        if img.height > 300 or  img.width > 300:
            img = img.resize((300, 300), Image.ANTIALIAS) #Image.NEAREST, Image.LANCZOS, Image.BILINEAR, Image.BICUBIC, Image.BOX, Image.HAMMING
            img.save(self.profile_pic.path, quality=100)
         
        img_thumb = img_thumb.resize((50, 50), Image.ANTIALIAS)
        img_thumb.save(self.profile_pic_thumb.path, quality=100)

  
    def delete(self, *args, **kwargs):
        storage1, path1 = self.profile_pic.storage, self.profile_pic.path
        storage2, path2 = self.profile_pic_thumb.storage, self.profile_pic_thumb.path
        if path1 != images_dir("DefaultUserIcon.png") and path2 != images_dir("DefaultUserIcon.png"):
            storage1.delete(path1)
            storage2.delete(path2)
        else:
            pass
  
    def __str__(self):
        return self.user.username

 

auths/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User
from django.forms import Textarea



class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    
    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'password_confirm')

class UserProfileInfoForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False, label="Select a file")
    class Meta():
        model = UserProfileInfo
        fields = [
            'profile_pic',
            'biography',
        ]

        widgets = {
            'biography': Textarea(attrs={'cols': 25, 'rows': 5, 'class': "form-control", 'style': "background:white; color:black"}),
        }

class ProfileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "control",'disabled': "disabled",'style': "width:100%; border:none!important; padding:2px 5px; background:none; color:black"}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control",'style': "background:white; color:black"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': "control",'disabled': "disabled",'style': "width:100%; border:none!important; padding:2px 5px; background:none; color:black"}))
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

auths/views.py
from med.templatetags.functions_extras import LoggedInSuccessMessage, UserIsConnect, InactiveAccountMessage, IncorectLoginInfosMessage, SuccessUpdateMessage, SuccessSaveMessage, RequireAuthenticateMessage, LogoutSuccessMessage
from django.shortcuts import render, redirect
from .forms import UserForm, UserProfileInfoForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import UserProfileInfo

from django.contrib import messages

def user_register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        password_confirm = request.POST.get('password_confirm')
        profile_pic = request.POST.get('profile_pic')
        user = authenticate(username=username, password=password)
        if password == password_confirm:
            if user_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user

                if profile_pic != "":
                    profile.profile_pic = request.FILES['profile_pic']
                    profile.profile_pic_thumb = request.FILES['profile_pic']

                try:
                    profile.save()
                    login(request, user)
                    datas = UserProfileInfo.objects.filter(user_id=str(user.id))
                    for data in datas:
                        request.session['small_user_profile_img_url'] = str(data.profile_pic_thumb)
                        request.session['large_user_profile_img_url'] = str(data.profile_pic)
                    registered = True
                    messages.success(request, SuccessSaveMessage(request))
                    return HttpResponseRedirect(reverse('profile'))
                except:
                    pass
            else:
                print(user_form.errors, profile_form.errors)
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
   
    return render(request, 'auths/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered, 'go_to_previous_page': UserIsConnect(request), 'text_transform':True})
 
def user_login(request):
    error = ""    

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        nxt = request.POST.get('next')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                datas = UserProfileInfo.objects.filter(user_id=request.user.id)

                for data in datas:
                    request.session['small_user_profile_img_url'] = str(data.profile_pic_thumb)
                    request.session['large_user_profile_img_url'] = str(data.profile_pic)
                
                messages.info(request, LoggedInSuccessMessage(request))
                if nxt:
                    return redirect(nxt)
                else:
                    return HttpResponseRedirect(reverse('home'))
            else:
                error = InactiveAccountMessage(request)
        else:
            error = IncorectLoginInfosMessage(request)
      
    return render(request, 'auths/login.html', {'error': error, 'go_to_previous_page': UserIsConnect(request), 'text_transform': True})

@login_required
def user_profile(request):
    Image_is_not_save = False
    query_user = User.objects.get(pk=request.user.id)
    Image_profile_form = UserProfileInfoForm(data=request.POST)

    if UserProfileInfo.objects.filter(user_id=request.user.id):
        query_profile = UserProfileInfo.objects.get(user_id=request.user.id)
        profile_form = UserProfileInfoForm(instance=query_profile)
    else:
        profile_form = UserProfileInfoForm()

    user_form = ProfileForm(instance=query_user)
    
    if request.method == 'POST':
        user = User.objects.get(pk=request.user.id)
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()

        pic = request.POST.get('profile_pic')

        if UserProfileInfo.objects.filter(user_id=request.user.id):
            profile = UserProfileInfo.objects.get(user_id=request.user.id)
            if pic != "":
                profile.delete()
        else:
            profile = profile_form.save(commit=False)
            profile.user = user

        if pic != "":
            profile.profile_pic = request.FILES['profile_pic']
            profile.profile_pic_thumb = request.FILES['profile_pic']

        profile.biography = request.POST.get('biography')

        try:
            profile.save()
            messages.success(request, SuccessUpdateMessage(request))
            return HttpResponseRedirect(reverse('profile'))
        except:
            Image_is_not_save = True

    datas = UserProfileInfo.objects.filter(user_id=request.user.id)

    for data in datas:
        request.session['small_user_profile_img_url'] = str(data.profile_pic_thumb)
        request.session['large_user_profile_img_url'] = str(data.profile_pic)
    return render(request, 'auths/profiles.html', {"user_form": user_form, 'profile_form': profile_form, 'Image_profile_form': Image_profile_form, 'Image_is_not_save': Image_is_not_save})

def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        messages.info(request, LogoutSuccessMessage(request))
    else:
        messages.info(request, RequireAuthenticateMessage(request))
    
    return HttpResponseRedirect(reverse('login'))

def user_params(request):
    return render(request, 'auths/userparams.html', {})

auths/templates/auths/login.html
{% extends 'layouts/_base.html' %}
{% load functions_extras %}

{% block nav_footer %}{% endblock nav_footer %}

{% block content %}
<div class="container">
       <div class="row mt-3">
            <div class="col-md-4"></div>
                <div class="col-md-4">
                        <h1 style="text-align: center;">{{ "page de connexion"|trans:request }}</h1>

                        {% include 'layouts/_messages.html' %}
                        {% if error %}
                        <div class="btn btn-danger">{{ error }}</div>
                        {% endif %}
                        
                        <form data-parsley-validate method="post" action="{% url 'login' %}" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{request.GET.next}}">
                            <div class="form-group">
                                <label for="username">{{ "identifiant"|trans:request }}:</label>
                                <input class="form-control" type="text" name="username" placeholder="{{ 'identifiant'|trans:request }}" data-parsley-minlength="3">
                            </div>
                        
                            <div class="form-group">
                                <label for="password">{{ 'mot de passe'|trans:request }}:</label>
                                <input class="form-control" type="password" name="password" placeholder="{{ 'mot de passe'|trans:request }}">
                            </div>
                            <input class="btn btn-primary" type="submit" name="" value="{{ 'connexion'|trans:request }}">
                            <a style="float:right;font-size:smaller;text-decoration:none;" href="{% url 'register' %}">{{ "s'enrégistrer"|trans:request }}</a>
                        </form>
                </div>
            <div class="col-md-4"></div>
       </div>
</div>
{% endblock %}

auths/templates/auths/profiles.html
{% extends 'layouts/_base.html' %}
{% load static %}

{% block nav_footer %}{% endblock nav_footer %}
{% load functions_extras %}
{% block content %}

<div style="margin-top: 50px;" class="container">
    <div class="row mt-3">
        <div class="col-md-2"></div>
            <div class="col-md-8"> 

                {% include 'layouts/_messages.html' %}
                
                <div class="row">
                    <div class="col-md-6">
                        <h2 style="text-align: left; color:rgb(1, 44, 30)">{{ 'votre profile'|trans:request }}</h2>
                        <div class="row">
                            <div class="col-md-12">
                                {% if Image_is_not_save %}
                                <h2 style="text-align: center; color:rgb(117, 5, 5)">{{ "Problème avec votre Fichier Joint."|trans:request }}<br>{{ "Choisir Une Image!"|trans:request }}</h2>
                                {% else %}
                                <img src="/media/{{ request.session.large_user_profile_img_url }}" alt="{{ 'image de profile'|trans:request }}">
                                {% endif %}
                            </div>
                            <div class="col-md-12">
                                <h2>{{ user_form.username }}</h2>
                                <h5>{{ user_form.email }}</h5>
                            </div>
                        </div> 
                    </div>
                    <div class="col-md-6">
                        <form data-parsley-validate method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="text-warning" for="last_name">{{ 'nom'|trans:request }} <span class="text-danger">*</span> </label>
                                {{ user_form.last_name }}
                            </div>
                            <div class="form-group">
                                <label class="text-warning" for="first_name">{{ 'prénoms'|trans:request }} <span class="text-danger">*</span> </label>
                                {{ user_form.first_name }}
                            </div>
                            <div class="form-group">
                                <label class="text-warning" for="username">{{ 'biographie'|trans:request }} </label>
                                {{ profile_form.biography }}
                            </div>

                            <div class="form-group">
                                <label class="text-warning" for="profile_pic">{{ "image de profile"|trans:request }}</label>
                                <div class="form-control">
                                    <label class="btn btn-default" id="profile_pic_label" for="id_profile_pic">
                                        <div class="row">
                                            <div id="picture_name_source" class="col-md-6 col-6">
                                                {{ "choisir une image"|trans:request }}
                                            </div>
                                            <div id="picture_name_cible" class="col-md-6 col-6"></div>
                                        </div>
                                    </label>
                                    {{ Image_profile_form.profile_pic}}
                                </div>
                            </div>

                            <!-- <a href="" onclick="document.getElementById('fileID').click(); return false;">choisir</a> -->
                            
                            <!-- <input onChange="getFileName(this.id,document.getElementById('cible'))" type="file" id="fileID">
                            <input id="cible" type="text" value=""> -->


                            
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">{{ 'mettre à jour'|trans:request }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>

</div>
{% endblock %}

auths/templates/auths/registration.html
{% extends 'layouts/_base.html' %}
{% load static %}
{% load functions_extras %}
{% block nav_footer %}{% endblock nav_footer %}

{% block content %}
<div class="container">
        <div class="row mt-3">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% if not registered %}
                    <h2 style="text-align: center;">{{ "inscription"|trans:request }} </h2>
        
                    {% if error %}
                    <div class="btn btn-danger">{{ error }}</div>
                    {% endif %}

                    <form data-parsley-validate method="post" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-md-6">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="text-warning" for="last_name">{{ "nom"|trans:request }}<span class="text-danger">*</span> </label> 
                                    {{ user_form.last_name }}
                                </div> 
                                <div class="form-group">
                                    <label class="text-warning" for="first_name">{{ "prenoms"|trans:request }}<span class="text-danger">*</span> </label> 
                                    {{ user_form.first_name }}
                                </div> 
                                <div class="form-group">
                                    <label class="text-warning" for="username">{{ "nom utilisateur"|trans:request }}<span class="text-danger">*</span> </label> 
                                    {{ user_form.username }}
                                </div> 
                                <div class="form-group">
                                    <label class="text-warning" for="email">{{ "email"|trans:request }}<span class="text-danger">*</span> </label> 
                                    {{ user_form.email }}
                                </div>
                                
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="text-warning" for="password">{{ "mot de passe"|trans:request }}<span class="text-danger">*</span> </label> 
                                    {{ user_form.password }}
                                </div>  
                                <div class="form-group">
                                    <label class="text-warning" for="password_confirm">{{ "confirmer le mot de passe"|trans:request }}<span class="text-danger">*</span> </label> 
                                    {{ user_form.password_confirm }}
                                </div>
                                <div class="form-group">
                                    <label class="text-warning" for="profile_pic">{{ "image de profile"|trans:request }}</label> 
                                    <div class="form-control">
                                        <label class="btn btn-default" id="profile_pic_label" for="id_profile_pic">
                                            <div class="row">
                                                <div id="picture_name_source" class="col-md-6 col-6">
                                                    {{ "choisir une image"|trans:request }}
                                                </div>
                                                <div id="picture_name_cible" class="col-md-6 col-6"></div>
                                            </div>
                                        </label> 
                                        {{ profile_form.profile_pic}}
                                    </div> 
                                </div>  

                                
                                <div style="margin-top: 48px;" class="form-group">
                                    <input class="btn btn-primary" type="submit" name="" value="Register">
                                    <a style="float:right;font-size:smaller;text-decoration:none;" href="{% url 'login' %}">{{ "se connecter"|trans:request }}</a>
                                </div>
                                
                            </div>
                        </div>
                    </form>
                {% endif %}
            </div>
            <div class="col-md-2"></div>
        </div>

</div>
{% endblock %}

auths/templates/auths/userparams.html
{% extends 'layouts/_base.html' %}
{% load static %}
{% load functions_extras %}

{% block nav_footer %}{% endblock nav_footer %}


{% block content %}
    <h1>USER PARAMS</h1>

    <embed src={% static 'files/data.pdf' %} width=100% height=1000 type='application/pdf' />
    
{% endblock %}